[build]
  command = "npm run build"
  publish = "dist"

[images]
  remote_images = ["https://windowsupplydirectltd.co.uk/.*"]

# If using Netlify Edge Functions, also add:
[build.environment]
  NUXT_IMAGE_DOMAINS = "windowsupplydirectltd.co.uk,secure.woonuxt.com"